### ISSUE TITLE
Doubt during plugin install

### ISSUE THREAD

**Issue by vinnycrazzy** [ezrpg/ezRPG-1.2.x#57]
Hello, good Everything?
I Have a Doubt. What is the content of XML and certain positions of the files and folders to install a plugin?

**Comment by ferdis** [comment]
You should be able to just copy the plugin(also modules) into the `modules` directory.
Depending on the module you may also need to add some things to the database.

What plugin/module are you trying to install?

_P.S. Also note that Github is primarily used for tracking bugs, feature requests and similar aspects related to the development of ezRPG. If you'd like help with using ezRPG please make a post on the [ezRPG Forums](http://community.ezrpgproject.net/)._

**Comment by vinnycrazzy** [comment]
Good Morning.
I made a copy of the City module, I edited names of the files and information in the class, I inserted the information in the database, plugins and plugins_meta and even then I can not access the URL - index.php? Mod = MyCustomModule

What plugin / module are you trying to install? - I'm going to create my own plugins, the old ones do not work!

**Comment by uaktags** [comment]
Please continue this topic over at the forums unless there's a specific issue that we can test and evaluate. I'd be more than happy to assist with module development in the forums.
